[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  branch = "release-1.12"
  name = "k8s.io/apimachinery"

[[constraint]]
	branch = "release-1.12"
	name = "k8s.io/metrics"

[[constraint]]
  branch = "release-9.0"
  name = "k8s.io/client-go"
